### ISSUE TITLE
Nuget packages fail to load after pressing F5

### ISSUE THREAD

**Issue by mimisasouvanh** [OfficeDev/Word-Add-in-MarkdownConversion#3]
After I download the solution, open it in VS2015, and finally press F5 to build the solution, I get this error:
"The project references NuGet packages(s) that are missing on this computer. Use NuGet Package Restore to download them. The missing file is ..\packages\Microsoft.Net.Compilers.1.0.0\build\Microsoft.Net.Compilers.props" in Project Word-Add-in-JavaScript-MDConversionWeb and File Word-Add-in-JavaScript-MDConversionWeb.csproj.
I managed to find a fix by using a suggestion on Stackoverflow: https://stackoverflow.com/questions/32254439/nuget-packages-are-missing

Here are the steps I used to fix:
1. In File Explorer, navigate to the ..\Word-to-MarkdownConversion\Word-Add-in-JavaScript-MDConversionWeb\ folder and open the Word-Add-in-JavaScript-MDConversionWeb.csproj file with a text editor. 
2. Find the tag <Target Name="EnsureNugetPackageBuildImports"...></Target> and remove it and everything inside the tag, or comment it out.
3. Save the file and close it.
4. In Visual Studio, select "Reload" in the "File Modification Detected" window.
4. Press F5 to build the solution.

**Comment by Rick-Kirkham** [comment]
@mimisasouvanh 
Thanks. I'll try to reproduce on a clean machine. If I can, I'll just remove those lines from the repo copy of the csproj file. VS adds those lines when the project is created, but this sample doesn't actually have any compile-able C# code, so it doesn't have a ..\packages folder.
