### ISSUE TITLE
Sample isn't loading in VS 2017

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/Word-Add-in-MarkdownConversion#4]
Code sample results in an error. Maybe a project config setting?

**Comment by Rick-Kirkham** [comment]
What is the error and when do you see it?

**Comment by jasonqsong** [comment]
Doesn't load in VS 2019 either. I guess it's the same issue.

First I saw "Missing the following two NuGet packages"
Microsoft.Net.Compilers.1.0.0
Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0

I manually added the two outdated packages in NuGet packages.config
```xml
<packages>
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="1.0.0" targetFramework="net45" />
  <package id="Microsoft.Net.Compilers" version="1.0.0" targetFramework="net45" developmentDependency="true" />
</packages>
```

Now the project built successfully. But Office reports "A problem occurred while trying to reach this add-in"

![image](https://user-images.githubusercontent.com/6178947/60043251-3eb7dd80-96f2-11e9-8b9a-69df3a0bf2ed.png)

I'm completely new to Office Add-in development and I've got no idea about the place to find the furthur error logs in Word.

**Comment by Rick-Kirkham** [comment]
A couple of things to try: 
1. When you see this error try opening `https://localhost:44356/Home.html` in a browser window. You should get errors, but it might be instructive to see what the errors say. 
2. Intall the [Fiddler](https://www.telerik.com/fiddler) tool. When you press **Open Converter**,  there should be a call in Fiddler to `https://localhost:44356/Home.html`. See what the Response object to that call says.

**Comment by Rick-Kirkham** [comment]
@jasonqsong 
I'm going to close this issue. If you are still having this problem, please let me know in a comment.
