### ISSUE TITLE
VS 2017 and Word 2016 Error

### ISSUE THREAD

**Issue by ngelotte** [OfficeDev/Word-Add-in-MarkdownConversion#6]
I had to cleanup the csproj and loaded new Nuget packages for Microsoft.CodeDom.Providers.DotNetCompilerPlatorm and Microsoft.Net.Compilers to get the project to run. But once I got it running there seems to be a problem with the interaction between word and the javascript file. When I click on the Convert document to Markdown function it runs into an error. The Log shows:
Error: InvalidArgument: InvalidArgument
Debug info: {"code":"InvalidArgument","message":"InvalidArgument","errorLocation":""}
Trace info: []

When debugging through the javascript the command that is failing to run is on line 578 which is the code block that starts like this:
            return context.sync()
                .then(function () {
                    /*
                      Now that paragraphs are loaded, load the word ranges within them
                      that the queueConversionOfBoldAndItalicRanges method is going to process.
                    */
                    sharedDataObjects.paragraphs.items.forEach(function (paragraph) {

If I put a breakpoint on line 584 it is never hit but I don't know where in the function the error is occurring and the error is not very helpful. 

My Visual Studio version is 15.8.2 and my office version is 16.0.4639.1000 64-bit

**Comment by Rick-Kirkham** [comment]
It looks like your Office version is not recent enough. See the Prerequisites section of the readme.
